### ISSUE TITLE
V2.7 adding diaper changes stopped working?

### ISSUE THREAD

**Issue by cvocvo** [jcgoette/baby_buddy_homeassistant#115]
I upgraded to v2.7 and I have an automation tied to a zigbee button. On v2.6.7 I can press the button to record a wet/solid diaper. After upgrading to v2.7 this stopped working. I downgraded back to 2.6.7 and it works again. I tested by also just running the action from the automation. 

Any ideas? Starting timers still works fine. Here’s the yaml for the automation action: 

```
service: babybuddy.add_diaper_change
data:
  type: Solid
  time: "{{ now().strftime('%H:%M:%S') }}"
target:
  entity_id: sensor.baby_baby_van_oort

```
Thank you!
