### ISSUE TITLE
Automation Add Temperature

### ISSUE THREAD

**Issue by jonasv05** [jcgoette/baby_buddy_homeassistant#155]
So basically i created helper entities to select baby (have multiple), set the temperature, klik a button that triggers the automation.
Helpers:

- input_select.bb_select_baby
- input_number.bb_temperatuur
- input_button.bb_add_temperature

My Automation looks like this but the action-part refuses to work. Keeps setting the temperature & time back to 'none':
This is how i configure it:
```
alias: BabyBuddy_Add_Temperature
description: ""
triggers:
  - trigger: state
    entity_id:
      - input_button.bb_add_temperature
conditions: []
actions:
  - data:
      entity_id: >-
        sensor.baby_{{ states('input_select.bb_select_baby') | string }}_vervisch
      temperature: {{ states('input_number.bb_temperatuur') | float }}
      time: {{ now().strftime('%H:%M:%S') }}
    action: babybuddy.add_temperature
mode: single

```
This is what it changes to:
```
alias: BabyBuddy_Add_Temperature
description: ""
triggers:
  - trigger: state
    entity_id:
      - input_button.bb_add_temperature
conditions: []
actions:
  - data:
      entity_id: >-
        sensor.baby_{{ states('input_select.bb_select_baby') | string
        }}_vervisch
      temperature:
        "[object Object]": null
      time:
        "[object Object]": null
    action: babybuddy.add_temperature
mode: single

```
If i go to DeveloperTools > Templates I run the code and everything gets replaced fine. 
So I'm at my whit's end here.
Thank you in advance for suggestions!
If i get this to work I can expand on this and add more / other automations.
