### ISSUE TITLE
Expose Multiple Timers or Respect BB Timer types.

### ISSUE THREAD

**Issue by khobbits** [jcgoette/baby_buddy_homeassistant#156]
I'm using the Baby Buddy [official android app](https://github.com/babybuddy/babybuddy-for-android), which provides buttons to start multiple concurrent timers.

The timers have specific names such as 'Feeding-BBapp:1', 'Sleep-BBapp:2', 'Pumping-BBapp:4'.

This allows for a parent to be pumping at the same time the baby is either asleep, or feeding.

I was hoping to collect/display this data in home assistant, and mimic the functionality, of being able to start 'feeding'  timers, and I can do this:

```
          - action: babybuddy.start_timer
            target:
              entity_id: switch.baby_timer
            data:
              name: HA-Sleep-BBapp:2
```

However, when calling the service, to add a feeding/pump/sleep, it only (seems) to support the idea of "the currently active timer".

So it will pick the last started timer, rather than the correct timer for the activity.

**Comment by brianchirls** [comment]
I've had the same problem: my partner wants to pump at the same time I'm bottle-feeding our baby, so we need two timers at once. Where this gets extra tricky is that if I start the feeding timer in HA and manually make another timer for pumping inside BB, then HA gets all confused when I want to finish feeding 'cause it seems to assume there's only one timer at a time.

As a workaround, I've implemented timing entirely inside HA. Here's what one timer set-up looks like:

```yaml
input_boolean:
  feeding_active:
    name: Feeding Active

input_datetime:
  feeding_start_time:
    name: Feeding Start Time
    has_date: true
    has_time: true

template:
  - trigger:
      - trigger: time_pattern
        seconds: /1
      - trigger: state
        entity_id: input_boolean.feeding_active
    sensor:
      name: Feeding Elapsed Time
      #unit_of_measurement: s
      icon: mdi:timer
      state: >-
        {% if is_state('input_boolean.feeding_active','off') %}
           {{ '00:00:00' }}
        {% else %}
          {% set value = as_timestamp(now()) - state_attr('input_datetime.feeding_start_time', 'timestamp') %}
          {{ value|float|timestamp_custom("%H:%M:%S", False) |string }}
        {% endif %}
```

It's nice because the elapsed time sensor updates every second, and I can get live counter display going. I can also make the start time editable, which is useful if I forget to start the timer until I'm a few minutes into a feed/nap or whatever, and then I can back-date it before saving.
