### ISSUE TITLE
Unable to call services from HA

### ISSUE THREAD

**Issue by jampez77** [jcgoette/baby_buddy_homeassistant#27]
Adding tummy / sleep time always fails but i'm not sure why.

Here is my service data:

```
service: babybuddy.services_tummy_times_add
data: 
  child: sensor.baby_nandhra_pezone
  start: 2021-07-13 09:15
  end: 2021-07-13 09:20
```

Here is what the logs say 
`Cannot create tummy-times, check service fields`

Here is the baby sensor details as seen in HA.

```
id: 1
first_name: Baby
last_name: Nandhra-Pezone
birth_date: 2021-08-09
slug: baby-nandhra-pezone
picture: null
child_name: Baby_Nandhra-Pezone
endpoint: children
friendly_name: Baby Nandhra-Pezone
icon: mdi:baby-face-outline
```

From what i can see the service fields are right so I think something else might be going on here. Oddly though it did work the once but not since. The only thing i've changed since at all is the start and end times.
