### ISSUE TITLE
Add Sensor for Most Recent Timer

### ISSUE THREAD

**Issue by torrancew** [jcgoette/baby_buddy_homeassistant#37]
I'm building a Lovelace UI for BabyBuddy, and would like to be able to display the elapsed duration of a running timer, eg to be able to quickly tell how long a nap or feeding has been going on from within HA.

**Comment by engrbm87** [comment]
Hello @torrancew , I also display the elapsed duration for a running timer in my lovelace UI. Simply use the timer switch attribute 'Duration'. below is an example:
```yaml
  - type: attribute
    entity: switch.baby_last_timer # replace with your switch name
    attribute: duration
```
