### ISSUE TITLE
Ending Timer to ADD_Sleep - Lovelace Buttons

### ISSUE THREAD

**Issue by Borlean** [jcgoette/baby_buddy_homeassistant#40]
I'm able to start a timer using the "switch.NAME_last_time" entity but am having issues ending and logging the activity. My test trying to log sleep with the ADD_Sleep service, see below. Since i'm using the "switch.NAME_last_timer" button, it just deletes the previous timer. 

              - type: button # to start the timer, this works correctly. 
                tap_action:
                  action: toggle
                entity: switch.NAME_last_timer

              - type: button # Looking to stop the previous timer and log sleep. 
                type_action:
                  action: call-service
                service: add_sleep
                entity: switch.NAME_last_timer
                timer: true

**Comment by jcgoette** [comment]
You shouldn't be toggling the switch. You just call the service with the active switch entity.

**Comment by Borlean** [comment]
That works!

Thanks for the help.

            - type: button
                tap_action:
                  action: call-service
                  service: babybuddy.add_sleep
                  service_data:
                    timer: true
                  target:
                    entity_id: switch.NAME_last_timer
                icon: mdi:sleep
                name: Add Sleep
                show_state: false

**Comment by five2seven** [comment]
Any chance we can reopen this? I still can't get a working button to log sleep. 

Tried dozens of variations of this: 

`type: button
tap_action:
  action: call-service
  service: babybuddy.add_sleep
  service_data:
    timer: true
  target:
    entity_id: switch.finley_ondejko_timer #this is the only switch I have
entity: sensor.finley_ondejko_last_timer #the "last timer" is a sensor, not a switch
icon: mdi:power-sleep
name: Start/Stop Sleep Timer`

**Comment by jcgoette** [comment]
I think you have the nesting incorrect. Should be more like this:

```
tap_action:
  action: call-service
  service: babybuddy.add_sleep
  service_data:
    target:
      entity_id: switch.name_last_timer
    data:
      timer: true
```

**Comment by five2seven** [comment]
Now I get an error about extra keys:

``` Failed to call service babybuddy/add_sleep. extra keys not allowed @ data['target']

**Comment by jcgoette** [comment]
My first answer is probably incorrect. I am in front of my PC now and able to play with HA.

Are you trying to create a button on Lovelace dashboard? If so, it uses a GUI editor, which is nice and simple. Outputs this YAML:

```
type: button
tap_action:
  action: call-service
  service: babybuddy.add_sleep
  service_data:
    timer: true
  target:
    entity_id: switch.finley_ondejko_timer
```
