### ISSUE TITLE
No longer working with BabyBuddy Container

### ISSUE THREAD

**Issue by Borlean** [jcgoette/baby_buddy_homeassistant#79]
Using BabyBuddy v1.12.2 via docker, Home Assistant version 2022.9.7. My scripts for starting a timer and logging food (without a timer) no longer work. 

Start timer topped working: 
```
  - type: button
    tap_action:
      action: toggle
    entity: switch.child1_last_timer
    show_icon: true
    name: Start Timer
```

Button to log food stopped working: 
```
  - type: button
    tap_action:
      action: toggle
    entity: script.babybuddy_add_self_fed_snack
    name: Snack
```

With the below script:
```
babybuddy_add_self_fed_snack:
  alias: BabyBuddy Self Fed - Snack
  sequence:
  - service: babybuddy.add_feeding
    data:
      type: Solid food
      method: Self fed
      amount: 4
    target:
      entity_id: switch.child1_last_timer
  - service: notify.parents
    data:
      title: BabyBuddy
      message: "\U0001F33D\U0001F966 Snack \U0001F33D\U0001F966"
  mode: single
  icon: mdi:corn
```

However, I just rolled back to a backup of Home Assistant 9.6 and things appear to work at first glance. Does anyone know what broke with 9.7? Is anyone else having issues?
