### ISSUE TITLE
Using active timer for add service, doesn't delete timer

### ISSUE THREAD

**Issue by hockey6611** [jcgoette/baby_buddy_homeassistant#94]
When the timer switch is turned off, the timer is deleted.

However, when an 'add' service is used, the timer is stopped but not deleted. This leads to a build up of stopped timers. The below is the button I used for adding the current timer to tummy time.

```
cards:
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: babybuddy.add_tummy_time
      data:
        timer: true
        end: '00:00:00'
      target:
        entity_id: switch.test_tester_timer
```

Am I misunderstanding the use case for `service: babybuddy.add_tummy_time`? Or is there a way delete the time using these add services as well?
